name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust_version: [stable, "1.46.0"]

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-${{ matrix.rust_version }}-ci-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Rust toolchain
        run: rustup default ${{ matrix.rust_version }}

      - name: Build
        run: cargo build --locked --verbose

      - name: Run tests
        run: cargo test --locked --verbose

      - name: Rustfmt and Clippy
        run: |
          cargo fmt -- --check
          cargo clippy
        if: matrix.rust_version == 'stable'
